# Generated by Django 3.2.9 on 2023-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastroitens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('fornecedor', models.CharField(max_length=70, verbose_name='Empresa')),
                ('lote', models.TextField(max_length=10, verbose_name='Descrição')),
                ('validade', models.DateField(verbose_name='Validade')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
            ],
        ),
    ]
